var presetranks= [null, {
	"id": 1,
	"name": "USA",
	"rank": 1,
	"voting": false,
	"votes": 10001,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 2,
	"name": "Japan",
	"rank": 2,
	"voting": false,
	"votes": 0,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 3,
	"name": "TRX",
	"rank": 3,
	"voting": false,
	"votes": 1349,
	"cateId": 6,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 4,
	"name": "Satoshi Nakamoto",
	"rank": 4,
	"voting": false,
	"votes": 1000,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 5,
	"name": "Albert Einstein",
	"rank": 5,
	"voting": false,
	"votes": 0,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 6,
	"name": "China",
	"rank": 6,
	"voting": false,
	"votes": 13448,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 7,
	"name": "Apple",
	"rank": 7,
	"voting": false,
	"votes": 1000,
	"cateId": 5,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 8,
	"name": "BTC",
	"rank": 8,
	"voting": false,
	"votes": 1000,
	"cateId": 6,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 9,
	"name": "Singapore",
	"rank": 9,
	"voting": false,
	"votes": 0,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 10,
	"name": "Korea",
	"rank": 10,
	"voting": false,
	"votes": 0,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 11,
	"name": "New York",
	"rank": 11,
	"voting": false,
	"votes": 1000,
	"cateId": 3,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 12,
	"name": "Elon Musk",
	"rank": 12,
	"voting": false,
	"votes": 0,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 13,
	"name": "Justin Sun",
	"rank": 13,
	"voting": false,
	"votes": 1344,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 14,
	"name": "Canada",
	"rank": 14,
	"voting": false,
	"votes": 0,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 15,
	"name": "Germany",
	"rank": 15,
	"voting": false,
	"votes": 0,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 16,
	"name": "Taylor Swift",
	"rank": 16,
	"voting": false,
	"votes": 0,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 17,
	"name": "Justin Bieber",
	"rank": 17,
	"voting": false,
	"votes": 0,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 18,
	"name": "Isaac Newton",
	"rank": 18,
	"voting": false,
	"votes": 0,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 19,
	"name": "Leonhard Euler",
	"rank": 19,
	"voting": false,
	"votes": 1000,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 20,
	"name": "Jesus Christ",
	"rank": 20,
	"voting": false,
	"votes": 1000,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 21,
	"name": "Muhammad",
	"rank": 21,
	"voting": false,
	"votes": 0,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 22,
	"name": "Russia",
	"rank": 22,
	"voting": false,
	"votes": 0,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 23,
	"name": "Buddha Shakyamuni",
	"rank": 23,
	"voting": false,
	"votes": 0,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 24,
	"name": "India",
	"rank": 24,
	"voting": false,
	"votes": 0,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 25,
	"name": "France",
	"rank": 25,
	"voting": false,
	"votes": 0,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 26,
	"name": "United Kingdom",
	"rank": 26,
	"voting": false,
	"votes": 0,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 27,
	"name": "Brasil",
	"rank": 27,
	"voting": false,
	"votes": 0,
	"cateId": 1,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 28,
	"name": "Bill Gates",
	"rank": 28,
	"voting": false,
	"votes": 0,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 29,
	"name": "Shanghai",
	"rank": 29,
	"voting": false,
	"votes": 1344,
	"cateId": 3,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 30,
	"name": "Tokyo",
	"rank": 30,
	"voting": false,
	"votes": 0,
	"cateId": 3,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 31,
	"name": "Bangkok",
	"rank": 31,
	"voting": false,
	"votes": 0,
	"cateId": 3,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 32,
	"name": "Egyptian pyramids",
	"rank": 32,
	"voting": false,
	"votes": 0,
	"cateId": 4,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 33,
	"name": "Huawei",
	"rank": 33,
	"voting": false,
	"votes": 1344,
	"cateId": 5,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 34,
	"name": "Great Wall of China",
	"rank": 34,
	"voting": false,
	"votes": 1345,
	"cateId": 4,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 35,
	"name": "Samsung",
	"rank": 35,
	"voting": false,
	"votes": 0,
	"cateId": 5,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 36,
	"name": "Colosseum",
	"rank": 36,
	"voting": false,
	"votes": 0,
	"cateId": 4,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 37,
	"name": "London",
	"rank": 37,
	"voting": false,
	"votes": 0,
	"cateId": 3,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 38,
	"name": "Paris",
	"rank": 38,
	"voting": false,
	"votes": 0,
	"cateId": 3,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 39,
	"name": "BYD",
	"rank": 39,
	"voting": false,
	"votes": 1344,
	"cateId": 5,
	"creator": "TAx9Ak9jJP9hVcPpWWRVMVLr2bqHS4HtUW"
}, {
	"id": 40,
	"name": "VOTEIT",
	"rank": 40,
	"voting": false,
	"votes": 1001.01,
	"cateId": 6,
	"creator": "TCbLNGcJy1SzmoVrZvE1H1oY5mZbuzHhuM"
}, {
	"id": 41,
	"name": "ETH",
	"rank": 41,
	"voting": false,
	"votes": 1000.01,
	"cateId": 6,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 42,
	"name": "KFC",
	"rank": 42,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 43,
	"name": "McDonald\'s",
	"rank": 43,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 44,
	"name": "Coca-Cola",
	"rank": 44,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 45,
	"name": "Pepsi",
	"rank": 45,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 46,
	"name": "XRP",
	"rank": 46,
	"voting": false,
	"votes": 0.01,
	"cateId": 6,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 47,
	"name": "LINK",
	"rank": 47,
	"voting": false,
	"votes": 0.01,
	"cateId": 6,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 48,
	"name": "Mao Zedong",
	"rank": 48,
	"voting": false,
	"votes": 1344.01,
	"cateId": 2,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 49,
	"name": "Donald J. Trump",
	"rank": 49,
	"voting": false,
	"votes": 0.01,
	"cateId": 2,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 50,
	"name": "Roma",
	"rank": 50,
	"voting": false,
	"votes": 0.01,
	"cateId": 3,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 51,
	"name": "Beijing",
	"rank": 51,
	"voting": false,
	"votes": 1344.01,
	"cateId": 3,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 52,
	"name": "Los Angeles",
	"rank": 52,
	"voting": false,
	"votes": 0.01,
	"cateId": 3,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 53,
	"name": "Melbourne",
	"rank": 53,
	"voting": false,
	"votes": 0.01,
	"cateId": 3,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 54,
	"name": "Sydney",
	"rank": 54,
	"voting": false,
	"votes": 0.01,
	"cateId": 3,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 55,
	"name": "The Eiffel Tower",
	"rank": 55,
	"voting": false,
	"votes": 0.01,
	"cateId": 4,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 56,
	"name": "Dubai",
	"rank": 56,
	"voting": false,
	"votes": 0.01,
	"cateId": 3,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 57,
	"name": "Taj Mahal",
	"rank": 57,
	"voting": false,
	"votes": 0.01,
	"cateId": 4,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 58,
	"name": "The Statue of Liberty",
	"rank": 58,
	"voting": false,
	"votes": 0.01,
	"cateId": 4,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 59,
	"name": "The Grand Canyon",
	"rank": 59,
	"voting": false,
	"votes": 0.01,
	"cateId": 4,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 60,
	"name": "Great Barrier Reef",
	"rank": 60,
	"voting": false,
	"votes": 0.01,
	"cateId": 4,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 61,
	"name": "Las Vegas",
	"rank": 61,
	"voting": false,
	"votes": 0.01,
	"cateId": 3,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 62,
	"name": "Golden Temple",
	"rank": 62,
	"voting": false,
	"votes": 0.01,
	"cateId": 4,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 63,
	"name": "Canadian Rockies",
	"rank": 63,
	"voting": false,
	"votes": 0.01,
	"cateId": 4,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 64,
	"name": "Niagara Falls",
	"rank": 64,
	"voting": false,
	"votes": 0.01,
	"cateId": 4,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 65,
	"name": "Venice",
	"rank": 65,
	"voting": false,
	"votes": 0.01,
	"cateId": 3,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 66,
	"name": "Maldive",
	"rank": 66,
	"voting": false,
	"votes": 0.01,
	"cateId": 1,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 67,
	"name": "Victoria Falls",
	"rank": 67,
	"voting": false,
	"votes": 0.01,
	"cateId": 4,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 68,
	"name": "Hawaii",
	"rank": 68,
	"voting": false,
	"votes": 0.01,
	"cateId": 3,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 69,
	"name": "Angkor Wat",
	"rank": 69,
	"voting": false,
	"votes": 0.01,
	"cateId": 4,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 70,
	"name": "Himalayas",
	"rank": 70,
	"voting": false,
	"votes": 1344.01,
	"cateId": 4,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 71,
	"name": "Google",
	"rank": 71,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 72,
	"name": "Amazon",
	"rank": 72,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 73,
	"name": "Canon",
	"rank": 73,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 74,
	"name": "Toyota",
	"rank": 74,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 75,
	"name": "Honda",
	"rank": 75,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 76,
	"name": "Tesla",
	"rank": 76,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 77,
	"name": "Microsoft",
	"rank": 77,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 78,
	"name": "Martin Luther King Jr.",
	"rank": 78,
	"voting": false,
	"votes": 0.01,
	"cateId": 2,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 79,
	"name": "LTC",
	"rank": 79,
	"voting": false,
	"votes": 0.01,
	"cateId": 6,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 80,
	"name": "EOS",
	"rank": 80,
	"voting": false,
	"votes": 0.01,
	"cateId": 6,
	"creator": "TNk7BqY6Pe8zSYFFDp1sz45gAGMjLhF2iy"
}, {
	"id": 81,
	"name": "Nokia",
	"rank": 81,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 82,
	"name": "XMR",
	"rank": 82,
	"voting": false,
	"votes": 0.01,
	"cateId": 6,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 83,
	"name": "DASH",
	"rank": 83,
	"voting": false,
	"votes": 0.01,
	"cateId": 6,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 84,
	"name": "NEO",
	"rank": 84,
	"voting": false,
	"votes": 0.01,
	"cateId": 6,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 85,
	"name": "Alibaba",
	"rank": 85,
	"voting": false,
	"votes": 1000.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}, {
	"id": 86,
	"name": "Ford",
	"rank": 86,
	"voting": false,
	"votes": 0.01,
	"cateId": 5,
	"creator": "TNv3b2MwnMpAhw9FRmoKEELvtRXqjSuUkE"
}];
